version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: signa_postgres
    environment:
      POSTGRES_USER: signa
      POSTGRES_PASSWORD: signa123
      POSTGRES_DB: signa_db
    ports:
      - "5432:5432"
    volumes:
      - signa_pgdata:/var/lib/postgresql/data
volumes:
  signa_pgdata:
